### ISSUE TITLE
Error: GOOGLE_CLIENT_ID env variable is required when using the Google auth provider.

### ISSUE THREAD

**Issue by JamesTsetsekas** [vincanger/coverlettergpt#18]
I have folowed the documentation here https://wasp-lang.dev/docs/auth/social-auth/google and put my GOOGLE_CLIENT_ID & GOOGLE_CLIENT_SECRET in /home/ubuntu/dev/coverlettergpt/env.server but still get this error when running, and when going to login it spins and says Something went wrong :( eventually.

[ Server ] > server@0.0.0 validate-env
[ Server ] > node -r dotenv/config ./scripts/validate-env.mjs
[ Server ]
[ Server ] 🔍 Validating environment variables...
[ Server!] /home/ubuntu/dev/coverlettergpt/.wasp/out/sdk/wasp/server/auth/oauth/env.ts:10
[ Server!]       throw new Error(`${envVarName} env variable is required when using the ${providerName} auth provider.`);
[ Server!]             ^
[ Server!]
[ Server!]
[ Server!] Error: GOOGLE_CLIENT_ID env variable is required when using the Google auth provider.
[ Server!]     at ensureEnvVarsForProvider (/home/ubuntu/dev/coverlettergpt/.wasp/out/sdk/wasp/server/auth/oauth/env.ts:10:13)
[ Server!]     at <anonymous> (/home/ubuntu/dev/coverlettergpt/.wasp/out/sdk/wasp/server/auth/oauth/providers/google.ts:10:13)
[ Server!]     at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
[ Server!]     at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
[ Server!]     at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

**Comment by JamesTsetsekas** [comment]
I found the issue the .wasp/out/server/.env being created on wasp start only contains a DATABASE_URL value. is wasp start supposed to get the .env from /env.server, i can only get the node API to run on 3001 when i paste
